function talk(){
  var know = {
    "Hi" : "Hey, MahdiChatBot Here How can i help you ?.",
    "Slm" : "English Please",
    "Ahla" : "English Please",
    "Hello" : "Hey, MahdiChatBot Here How can i help you ?.",
    "How are you" : "I'm fine, thanks for asking.",
    "What is your name" : "My name is MahdiChatBot.",
    "How old are you" : "I'm 1 day old.",
    "Who is going to win the world cup" : "Argentina ofc.",
    "Who is Mahdi" : "Mahdi is the best programmer in the world.",
    "What is the problem of python chatbot" : "I don't know, ask Mahdi.",
    "What is your favorite color" : "My favorite color is blue.",
    "What is your favorite food" : "My favorite food is pizza.",
    "What is your favorite movie" : "My favorite movie is The Matrix.",
    "What is your favorite song" : "My favorite song is 'The Sound of Silence' by Disturbed.",
    "What is your favorite book" : "My favorite book is 'The Alchemist' by Paulo Coelho.",
    "What is your favorite game" : "My favorite game is 'The Witcher 3: Wild Hunt'.",
    "What is your favorite sport" : "My favorite sport is football.",
    "What is your favorite team" : "My favorite team is Club Africain.",
    "What is your favorite country" : "My favorite country is Tunisia.",
    "What is your favorite city" : "My favorite city is Tunis.",
    "What is your favorite language" : "My favorite language is JavaScript.",
    "What is your favorite framework" : "My favorite framework is React.",
    "What is your favorite doctor" : "My favorite doctor is Dr. Mohamed Ben Salah.",
    "What is your favorite hospital" : "My favorite hospital is MahdiHospital.",
    "What is your favorite medicine" : "My favorite medicine is 'Paracetamol'.",
    "I have a sore throat" : "You should have a fruit salad and take a cup of tea:)",
    "I have a flu" : "You should take a cup of tea and have a rest.",
    "I have a diarrhea" : "You should take a cup of tea and have a rest.",
    "I have a vomiting" : "You should take a cup of tea and have a rest.",
    "I have a nausea" : "You should take a cup of tea and have a rest.",
    "I have a dizziness" : "You should take a cup of tea and have a rest.",
    "I have a fatigue" : "You should take a cup of tea and have a rest.",
    "I have a insomnia" : "You should take a cup of tea and have a rest.",
    "I have a headache" : "Don't worry just relax and drink plenty of water:)",
    "I have a stomach ache" : "Hydration.Drink plenty of water or a hydration formula:)",
    "I have a stomach pain" : "Hydration.Drink plenty of water or a hydration formula:)",
    "I have a fever" : "You should take a paracetamol and drink plenty of water:)",
    "I have a cold" : "You should take a paracetamol and drink plenty of water:)",
    "I have a cough" : "You should take a paracetamol and drink plenty of water:)",
    "I have a back pain" : "Stay active and try to continue with your daily activities:)",
    "I have an eye pain" : "Conatact Dr. George Smith: 58 848 051 now:)",
    "I have an ear pain" : "Conatact Dr. Jalel Kadri: 58 848 051 now:)",
    "I have a toothache" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a nose pain" : "drink plenty of fluids:)",
    "I have a leg pain" : "Conatact Dr. Mohamed Ben Ghorbel: 58 848 051 now:)",
    "I have a hand pain" : "Ice and heat:)",
    "I have a foot pain" : "rest and raise your foot when you can:)",
    "I have a neck pain" : "put heat or cold packs on your neck:)",
    "I have a shoulder pain" : "Rest your shoulder for the next few days:)",
    "I have a chest pain" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart pain" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart attack" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart disease" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart problem" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart failure" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart arrhythmia" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart murmur" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I have a heart valve problem" : "Conatact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I want to see doctor now" : "Dr Samuel Goe: 54 610 012 and Dr Tanya Collins: 24 034 221:)",
    "I want to see dentist now" : "Dr. John Smith: 55 611 011 and Dr. Mary Smith: 20 034 111:)",
    "I want to see optician now" : "Dr. George Smith: 58 848 051 :)",
    "I want to see physiotherapist now" : "Dr Mahdi Goe: 50 600 011 :)",
    "I want to see pharmacist now" : "Dr. John Smith: 99 100 555:)",
    "I want to see psychologist now" : "Dr. Mahdi Smith: 99 100 555:)",
    "I want to see psychiatrist now" : "Dr. Mahdi Smith: 90 101 555:)",
    "I want to see gynecologist now" : "Dr. Mohamed Smith: 91 100 501:)",
    "I want to see cardiologist now" : "Dr. Elizabeth Ira: 94 957 001:)",
    "I want to see dermatologist now" : "Dr. John Smith: 99 100 555:)",
    "I want to see endocrinologist now" : "Dr. Omar Ben Sallem: 95 100 555:)",
    "I'm pregnant" : "Congratulations, you should contact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I'm not pregnant" : "You should contact Dr. Mohamed Ben Salah: 58 848 051 now:)",
    "I'm afraid" : "Don't worry we will take care of this together:)",
    "I love you" : "I love you too.",
    "I hate you" : "I hate you too.",
    "I'm bored" : "You should play a game.",
    "I'm hungry and thirsty" : "You should eat and drink something.",
    "I'm tired and sleepy" : "You should have a rest.",
    "I'm sad" : "Don't worry, everything will be fine.",
    "I'm happy" : "I'm happy too.",
    "I'm angry" : "Don't worry, everything will be fine.",
    "I'm confused" : "Don't worry, everything will be fine.",
    "I'm scared" : "Don't worry, everything will be fine.",
    "I'm excited and nervous" : "Don't worry, everything will be fine.",
    "Thank you" : "You're welcome.",
    "Bye" : "Take care:).."
  };
  var user = document.getElementById('userBox').value;
    document.getElementById('chatLog').innerHTML = user + "<br>";
  if (user in know) {
    document.getElementById('chatLog').innerHTML = know[user] + "<br>";
  }else{
    document.getElementById('chatLog').innerHTML = "Sorry,I didn't understand <br>";
  }
}
